import { Inter } from "next/font/google";
import "./globals.css";
import TranslationsProvider from "@/components/TranslationsProvider";
import initTranslations from "../../i18n";
import i18nConfig from "../../i18nConfig";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//+ const languages = ["en", "ur"];
// export async function generateStaticParams() {
//   return i18nConfig.locales.map((locale) => ({ locale }));
// }

// export async function generateStaticParams() {
//   return languages.map((lng) => ({ lng }));
// }

export default function RootLayout({ children }) {
  // const { t, resources } = initTranslations(locale, ["home"]);
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {console.log("locale", locale)} */}
        {/* <TranslationsProvider resources={resources} locale={locale} namespaces={["home"]}> */}
        {children}
        {/* </TranslationsProvider> */}
      </body>
    </html>
  );
}
